# Configuration for welcome - https://github.com/behaviorbot/welcome
newIssueWelcomeComment: >
  Congrats on opening your first issue on this repository! ğŸ‰<br>
  This is a automated message to help you avoid common pitfalls when asking for help online.<br>
  ğŸ‘‰ Be sure to:<br>
  * ğŸ‡¬ğŸ‡§ Communicate in English so everybody can understand you<br>
  * ğŸ“– Have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki) and [README](https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/README.md) for information<br>
  * ğŸ” Search for similar [issues (open and closed)](https://github.com/SpacehuhnTech/esp8266_deauther/issues?q=is%3Aissue+)<br>
  * âœï¸ Provide enough information to understand, recreate and help out with your problem<br>
  * â„¹ï¸ Let us know if you find a solution and please share it with us<br>
  * ğŸ“• Close the issue when your problem has been solved

newPRWelcomeComment: 

firstPRMergeComment: 
