# Configuration for welcome - https://github.com/behaviorbot/welcome
newIssueWelcomeComment: >
  Thanks for opening your first issue here! ğŸ‰<br>
  ğŸ‘‰ Be sure to:<br>
  1. ğŸ‡¬ğŸ‡§ Communicate in English so everybody can understand you<br>
  2. ğŸ“– Have a look at the [Wiki](https://github.com/spacehuhntech/esp8266_deauther/wiki) and [README](https://github.com/SpacehuhnTech/esp8266_deauther/blob/v2/README.md) for information<br>
  3. ğŸ” Search for similar [issues (open and closed)](https://github.com/SpacehuhnTech/esp8266_deauther/issues?q=is%3Aissue+)<br>
  4. âœï¸ Provide enough information to understand, recreate and help out with your problem<br>
  5. â„¹ï¸ Let us know if you find a solution and please share it with us<br>
  6. ğŸ“• Close the issue when your problem has been solved

newPRWelcomeComment: 

firstPRMergeComment: 
